### ISSUE TITLE
Contrib Module?

### ISSUE THREAD

**Issue by dylf** [makinacorpus/drupal-sf-dic#5]
I have been looking for ways to write more "forward compatible" code in a large legacy d7 project, to reduce friction if and when we finally do a d8 migration. I'm hoping to leverage other folks efforts instead of "reinventing the wheel".

Is this project something you folks would be interested in contributing to drupal.org?

**Comment by pounard** [comment]
We could create the project and regularly push this repo on drupal.org to keep in sync, it would work. But you know, if your project is composer based, you don't need to have it on drupal.org.

**Comment by pounard** [comment]
> I have been looking for ways to write more "forward compatible" code in a large legacy d7 project

This was the original goal of this module, but you have to be aware that it's far from complete, and most interfaces are locked onto Drupal 8.1, which is now quite old.

I personnally only ported one module (a huge one though) from 7.x to 8.6 that was using this module, I achieved it without too much pain, but it was not automatic, you have to know that. It still saved me a lot of time because all the OOP code was good to go as-is in 8.x (most of it anyway).

**Comment by dylf** [comment]
Yeah my thought was setting it up as a project on d.o, is that it may be more visible to Drupal contributors. I think getting Symfony's dependency injection container in my project, and abstracting away some of the Drupal API into services would be really nice. We are working on a project that seems to be riding d7 out till EOL.

**Comment by pounard** [comment]
We have a few as well, that's why this module exists. We never intended to provide it as a drupal project, since apart from visibility, it wouldn't bring any added value. I think that now, there's not much people interested in d7 anymore. If you see any blocker about this, please tell me.
